language:
  - swift
osx_image: xcode11.2
cache:
  - bundler
  - cocoapods
before_install:
  - bundle install
  - bundle exec pod keys set MarvelApiKey $MARVEL_API_PUBLIC VSMarvelApp
  - bundle exec pod keys set MarvelPrivateKey $MARVEL_API_SECRET VSMarvelApp
  - bundle exec pod repo update
script:
  - bundle exec fastlane scan
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - secure: glKNHgqbvC/MZp9724Tf/1RPgT+M6DeK4MgDA9nfISmUabomh/i9IDS17DI+Exowm7g19Wv60mZdOQnkZ12XsviPponcnzxfkDXZjoeShcJGfRt4Tazd27IvRWrcZ/Q0JXWgt683/LG2ngkQRPtgT0jl10uTckEmKWDdJ1vPQ3lV9AMlDy+zHYW6dkOM1wnH9F7e3KIAALSICAixZihgocxL3dLuFkQuTzELLl9jSOuA/eMbpKJWKSBLDMlMDCy498eWX+HD+xKuUc22iqHIk7Mfkzd6vZvJ5cWEenfxCt2gCx95yQryecpWKYBiAuNTAKtdx5wVLRHVL+GKcOf7m4h/3Zdaj3itlQlNj7r88g5UPjl0JLxtoWBrZwASpHG+bTRknYKSgRDdHuNrXmH6DpvpgIUHt8IzzvnJYzwb8v/dp1H99xzXXH/ho/788mLtITZd9XwXd84cGnqGY98mwoMDEHuQJ+VxDBYkuDW4EbHyRCtu2RncJMlWhHuVP7Lke6k8beif5p3DQMZxr3QyFCe3pip7M1IZXFPtdKqFFXZu39T+/HSjW3xHFMDdqlPovwyoeepDAEOG95hy5aGUdWaY9xzrjeXm0znOrkFeSDNcKsIrftNctQMpDknP3iyoXw4RVbL5f/sOQI9T8RYghWduoh79tN1/0fmR+yAdGm0=
    - secure: C1DHfZrZkZPsF0eirmKaGqvHGa7Ju3SfKkJ7xc7BF6CjuvtF3skMMujwAPuFkfrILAzNjlezgghdQkQQp7DB2JpC+ApMujJe73GaP7/ppLjN7DiNf+3JupRcrgum+uAG+TQivbm7C9TnE2EJL9/15gN2GcLZy41PD9Lf+CrtkWVLDNANY1wfz+SkVHaKzukKivVyNCf1fkKlre8arbB2dOQGBne1YbSGqRCFVuh0q2VlzOgoo9ViDl0DX0JJFC4bl8OJT9hLUut5eWGO+xDIAHvKlUAdD/l8A8sMocOG+YW3i86rlu6hYBE33VIOtaoJcP+JrR2RK6RDUp20djwl9vqXDYarBqBCh/45Ug3Wwtv5CyyBhPSfrWUHsz0nyMRE2H8wbzbakJF9BwXbWmPRTdwG1gtYdI7u/IL57couZRZd6oLakxhBZXWW5r21HSSO40NRXQP4BEsjdmk3RO27SCmeL5J6R5Cb65n7wnBAxcbE9FxTvIeH17sMlbgCsBfe/2qZAqmo1/I6jgpv1HSP39igH6CA+hASrmA5kqzsiK88TkEK91nl7azp3xmuMiNaCim0PGsDJCMejfjArsGVSla9k+fPC9o3FTRcxNOYealm4PRGyASCnszmhZaw9B2ThA2gI2evh1GPKgeb899ML33Q4DlF6cwZ8tRXwfmBdQo=
